name: tomato_manager
description: FreshTomato Router Manager - Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dartssh2: ^2.9.0
  flutter_riverpod: ^2.5.1
  riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  fl_chart: ^0.66.2
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  connectivity_plus: ^4.0.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
